language: node_js
node_js:
  - "node"
  - "10"
  - "8"

before_script:
  - npm ci

script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - npm run test:coveralls
  - npm run typedoc
