FROM node:24-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm ci && npm cache clean --force

# Bundle app source
COPY eslint.config.mjs tsconfig.json /usr/src/app/
COPY src /usr/src/app/src
COPY config /usr/src/app/config
COPY test /usr/src/app/test

CMD [ "npm", "test" ]
